// src/components/layout/Header.vue
<script setup lang="ts">
const headerTitle =
  "Product Engineer at Pleo. Originally from Manchester, currently living in Berlin.";
</script>

<template>
  <header class="grid sm:grid-cols-[1fr_113px] gap-8">
    <h1 className="font-normal font-serif text-[28px] sm:text-[38px] leading-[1.2] text-foreground">
      {{ headerTitle }}
    </h1>
  </header>
</template>

// apps/web/src/components/header.tsx
export const Header = () => {
	return (
		<header className="grid sm:grid-cols-[1fr_113px] gap-8">
			<h1 className="font-normal font-serif text-[28px] sm:text-[38px] leading-[1.2] text-foreground">
				Frontend Engineer at Pleo. Originally from Manchester, currently living
				in Berlin.
			</h1>
		</header>
	)
}
